version: '3'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chat
      POSTGRES_DB: chat
    volumes:
      - postgres:/var/lib/postgresql/data

  broker:
    image: apache/kafka:latest
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://localhost:9093,PLAINTEXT_HOST://broker:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://broker:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_LOG4J_ROOT_LOGLEVEL: DEBUG
    ports:
      - 9092:9092
    expose:
      - 29092

  broker_setup:
    image: apache/kafka:latest
    command: ["/opt/kafka/bin/kafka-topics.sh", "--bootstrap-server", "broker:29092", "--create", "--if-not-exists", "--topic", "messages"]
    depends_on:
      - broker

  api:
    env_file:
      - api.env
    build:
      context: ..
      dockerfile: deploy/Dockerfile.api
    command: ["uvicorn", "main:app", "--reload", "--port", "80", "--host", "0.0.0.0"]
    restart: always
    depends_on:
      - db
      - broker
    ports:
      - "8203:80"

  pusher:
    env_file:
      - pusher.env
    build:
      context: ..
      dockerfile: deploy/Dockerfile.pusher
    restart: always
    depends_on:
      - db
      - broker
    ports:
      - "18001:18001"

volumes:
  postgres:
